### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [hq-developer/hqrevenue-pixel-template#1]
https://github.com/hq-developer/hqrevenue-pixel-template/blob/57c66730dc48c8afd19774f4dd43267bf34bfc72/template.tpl#L106-L113

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by hq-developer** [comment]
Hello @semisight I hope the latest update got he issue fixed. Also I have updated the metadate.yml file.

Please, let me know if something else is pending.

All the best!

**Comment by semisight** [comment]
Apologies for the long wait. Your template should be available in Gallery momentarily.
